Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian12"

    # Create internal network
    config.vm.network "private_network", ip: "192.168.56.2"

    # connect internal \ external ports
    config.vm.network "forwarded_port", guest: 8082, host: 8080, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"

    # share data. set and change default html
    config.vm.synced_folder "../page1", "/var/www/html"
    config.vm.synced_folder "../page1", "/var/www/a.example.com"
    config.vm.synced_folder "../page2", "/var/www/b.example.com"

    config.vm.provision "file", source: "../data/a.example.com.conf", destination: "tmp/"
    config.vm.provision "file", source: "../data/b.example.com.conf", destination: "tmp/"
    config.vm.provision "file", source: "../data/hosts", destination: "tmp/"
    config.vm.provision "file", source: "../data/ports.conf", destination: "tmp/"

    # Install Apache
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y apache2
        sudo apt-get install -y php libapache2-mod-php
        mv -f tmp/b.example.com.conf /etc/apache2/sites-available/
        mv -f tmp/a.example.com.conf /etc/apache2/sites-available/
        mv -f tmp/hosts /etc/
        mv -f tmp/ports.conf /etc/apache2/ports.conf
        sudo ln -sf /etc/apache2/sites-available/b.example.com.conf /etc/apache2/sites-enabled/b.example.com.conf
        sudo ln -sf /etc/apache2/sites-available/a.example.com.conf /etc/apache2/sites-enabled/a.example.com.conf
        sudo systemctl restart apache2
    SHELL

end
