Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian12"

    # Create internal network
    config.vm.network "private_network", ip: "192.168.56.2"

    # connect internal \ external ports
    config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

    # share data
    config.vm.synced_folder "../data", "/var/www/html"

    # Install Apache
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y apache2
    SHELL
end