FROM jenkins/jenkins:latest

LABEL maintainer="pwd1390@mail.ru"

USER root

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

RUN jenkins-plugin-cli \
    --plugins \
    git 

# RUN /usr/local/bin/install-plugins.sh git
