version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.Jenkins
    image: hometask-image-jenkins:latest
    ports:
      - "80:8080"
  nexus:   
    build:
      context: .
      dockerfile: Dockerfile.Nexus3
    image: hometask-image-nexus:latest
    ports:
      - "81:8081"