---
#Playbook 1
- name: Slave playbook
  hosts: slave
  tags:
    - configuration
  gather_facts: no
  become: yes
  tasks:
    - name: install yum packages
      yum:
        name:
        - epel-release
        - mc
        - vc
        - sshpass
        state: present


#Playbook2
- name: Main playbook
  hosts: main
  tags:
    - configuration
  gather_facts: no  
  become: yes
  tasks:
    - name: install yum packages
      yum:
        name:
        - epel-release
        - mc
        - vc
        - sshpass
        - git
        state: present
