---
#Playbook1
- name: Main playbook
  hosts: main
  tags:
    - configuration
  gather_facts: no  
  become: yes
  tasks:
#     - name: Main -> install yum packages
#       yum:
#         name:
#         - epel-release   
#         - git       
#         state: present

#     - name: Main -> Replace after the expression till the end of the file (requires Ansible >= 2.4)
#       ansible.builtin.replace:
#         path: /etc/sysconfig/puppetserver
#         regexp: '-Xms2g -Xmx2g'
#         replace: 'JAVA_ARGS="-Xms256m -Xmx256m'

#     - name: Main -> Start puppet
#       systemd:
#         name: puppetserver
#         state: started

    # - name: Main -> Enable puppet
    #   systemd:
    #     name: puppetserver
    #     enabled: yes

    - name: Main -> Add ports to firewall
      firewalld:
        port: 8140/tcp
        state: enabled
        immediate: true
        permanent: true
      register: ports_added_to_firewalld

#Playbook2
- name: Slave playbook
  hosts: slave
  tags:
    - configuration
  gather_facts: no
  become: yes
  tasks:

    # - name: Slave - update /etc/puppetlabs/puppet/puppet.conf
    #   ansible.builtin.lineinfile:
    #     path: "{{ item.path }}"
    #     line: "{{ item.text }}"
    #   loop:
    #   - { path: '/etc/puppetlabs/puppet/puppet.conf', text: '[agent]\nserver = master.puppet\nruninterval = 1m'}
    #   - { path: '/etc/hosts', text: '192.168.56.40 master.puppet'}
      
    # - name: Slave -> puppet-agent start
    #   systemd:
    #     name: puppet
    #     state: started

    # - name: Slave -> puppet-agent enable
    #   systemd:
    #     name: puppet
    #     enabled: yes

    # – name: Slave -> Restart puppet service
    #   ansible.builtin.command: systemctl restart puppet

#Playbook3
- name: Main playbook post restart
  hosts: main
  tags:
    - configuration
  gather_facts: no  
  become: yes
  tasks:

    - name: Main post rst -> sign slaves certificates
      ansible.builtin.command:
        cmd: "{{ item.text }}"
      loop:
      - { text: '/opt/puppetlabs/bin/puppetserver ca sign --certname slave1.puppet'}
      - { text: '/opt/puppetlabs/bin/puppetserver ca sign --certname slave2.puppet'}
      