---
#Playbook1
- name: Main playbook
  hosts: main
  tags:
    - configuration
  gather_facts: no  
  become: yes
  tasks:
#     - name: Main -> install yum packages
#       yum:
#         name:
#         - epel-release   
#         - git       
#         state: present

#     - name: Main -> Replace after the expression till the end of the file (requires Ansible >= 2.4)
#       ansible.builtin.replace:
#         path: /etc/sysconfig/puppetserver
#         regexp: '-Xms2g -Xmx2g'
#         replace: 'JAVA_ARGS="-Xms256m -Xmx256m'

#     - name: Main -> Start puppet
#       systemd:
#         name: puppetserver
#         state: started

    # - name: Main -> Enable puppet
    #   systemd:
    #     name: puppetserver
    #     enabled: yes

    - name: Main -> Add ports to firewall
      firewalld:
        port: 8140/tcp
        state: enabled
        immediate: true
        permanent: true
      register: ports_added_to_firewalld

#Playbook2
- name: Slave playbook
  hosts: slave
  tags:
    - configuration
  gather_facts: no
  become: yes
  tasks:


    # - name: Slave -> Install or upgrade the net-tools package
    #   yum:
    #     name: net-tools
    #     state: latest
    
    # - name: Slave -> tcp ports facts
    #   listen_ports_facts:



    # - name: Slave -> print Ports Added
    #   debug:
    #     var: ports_added_to_firewalld

    # - name: Slave - update /etc/puppetlabs/puppet/puppet.conf
    #   ansible.builtin.lineinfile:
    #     path: "{{ item.path }}"
    #     line: "{{ item.text }}"
    #   loop:
    #   - { path: '/etc/puppetlabs/puppet/puppet.conf', text: '[agent]\r\nserver = master.puppet\r\nruninterval = 1m'}
    #   - { path: '/etc/hosts', text: '192.168.56.40 master.puppet'}
      
    # - name: Slave -> puppet-agent start
    #   systemd:
    #     name: puppet
    #     state: started

    # - name: Slave -> puppet-agent enable
    #   systemd:
    #     name: puppet
    #     enabled: yes