---
- name: Main playbook post restart
  hosts: slave
  tags:
    - configuration
  gather_facts: no  
  become: yes
  tasks:
    - name: Ensure 
       ansible.builtin.cron:
        name: "crono run"
        minute: "/2"
        job: "ls -alh > /dev/null"