Vagrant.configure("2") do |config|

    config.vm.synced_folder ".", "/vagrant", disabled: false    
    config.vm.box = "generic/centos8s"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 5
        vb.cpus   = 1
    end
    
    (1..2).each do |i|
        config.vm.define "slave#{i}.puppet" do |slave|
            slave.vm.network "private_network", ip: "192.168.56.4#{i}"
            slave.vm.hostname = "slave#{i}.puppet"
            slave.vm.provision "shell", inline: <<-SHELL
                yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
                yum install -y --downloadonly puppet-agent
            SHELL
        end
    end

    config.vm.define "master" do |master|
        master.vm.network "private_network", ip: "192.168.56.40"
        master.vm.provision "shell", inline: <<-SHELL
            yum install -y epel-release ansible vim mc
            yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm 
            yum install -y --downloadonly puppetserver git
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            echo "alias ll='ls -la'" >> /root/.bashrc
        SHELL
        # master.vm.provision :ansible_local do |ansible|
        #     ansible.playbook        = "playbook.yaml"
        #     ansible.limit         = "all"
        #     ansible.inventory_path = "inventory"
        # end
    end
end