Vagrant.configure("2") do |config|

    config.vm.synced_folder ".", "/vagrant", disabled: false    
    config.vm.box = "generic/centos8s"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus   = 1
    end
    
    (1..2).each do |i|
        config.vm.define "slave#{i}.puppet" do |slave|
            slave.vm.network "private_network", ip: "192.168.56.4#{i}"
            slave.vm.hostname = "slave#{i}.puppet"
            slave.vm.provision "shell", inline: <<-SHELL
                yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
                yum install -y --downloadonly -puppet-agent
                yum clean packages
                sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
                service sshd restart 
            SHELL
        end
    end

    config.vm.define "master" do |master|
        master.vm.network "private_network", ip: "192.168.56.40"
        master.vm.hostname = "master.puppet"
        master.vm.provision "shell", inline: <<-SHELL
            yum install -y ansible https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
            yum install -y --downloadonly puppetserver
            yum clean packages
            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart 
        SHELL
        master.vm.provision :ansible_local do |ansible|
            ansible.playbook       = "playbook.yaml"
            ansible.limit          = "all"
            ansible.inventory_path = "inventory"
        end
    end
end