
---
- name: Nexus
  hosts: nexus
  become: yes

  vars:
    nexus_admin_password: "changeme"
    nexus3_oss_api_username: "admin"
    nexus3_oss_api_password: "changeme"
    nexus_config_raw: true
    
    # create local nexus user
    nexus_local_users:
    - username: dev
      first_name: dev
      last_name: dev
      email: dev@company.com
      password: "dev"
      roles:
      - developers

    # nexus_repos_maven_hosted:
    # - name: company-project1
    #   version_policy: mixed
    #   write_policy: allow
    #   blob_store: default
    
    nexus_repos_raw_group:
    - name: raw-all
      member_repos:
      - raw-internal

    # create raw local nexus repo 
    nexus_repos_raw_hosted:
    - name: dev
      version_policy: release
      write_policy: allow # one of "allow", "allow_once" or "deny"
      blob_store: default

    nexus_roles:
      - id: Developpers # can map to a LDAP group id, also used as a key to update a role
        name: developers
        description: All developers
        privileges:
          - nx-all
  
  roles:
    - role: malec0101.temurin.java
      java_packages: "temurin-8-jdk"
    - { role: geerlingguy.apache }
    # RedHat/CentOS only
    #- { role: geerlingguy.apache, apache_create_vhosts: no, apache_remove_default_vhost: true, tags: ["geerlingguy.apache"] }
    - role: ansible-thoteam.nexus3-oss
