---
#Playbook 1
- name: Jenkins playbook
  hosts: jenkins
  tags:
    - configuration
  gather_facts: yes
  become: yes

  vars:
    jenkins_version: "2.442"
    jenkins_hostname: localhost
    jenkins_plugins_install_dependencies: true
    jenkins_plugins_state: present    
    jenkins_plugins:
      - credentials 
      - credentials-binding
      - locale
      - git
      - timestamper
      - pipeline-groovy-lib
      - workflow-basic-steps
      - workflow-cps
      - workflow-multibranch
      - pipeline-build-step
      - pipeline-input-step
      - pipeline-milestone-step
      - pipeline-stage-step
      - pipeline-model-definition 
      - configuration-as-code 
      - golang
      - prism-api

  pre_tasks:
    - include_tasks: debian-setup.yml
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins

  tasks:
    - name: Create dir
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        mode: '0755'
      loop:
      - { path: '/var/lib/jenkins/casc_configs' , state: 'directory'}
      - { path: '/var/lib/jenkins/jobs/build' , state: 'directory'}
    
    - name: Copy files for setup jenkins plugin
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
      - { src: '/vagrant/jenkins.yaml', dest: '/var/lib/jenkins/casc_configs/jenkins.yaml' }
    
    - name: copy job 'build'
      copy: src=/vagrant/build/ dest=/var/lib/jenkins/jobs/build/ remote_src=yes directory_mode=yes
    
    - name: Stop Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: stopped

    - name: Start Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes 

  post_tasks:
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8080/"
        status_code:
          - 200
          - 403