---
#Playbook 1
- name: Jenkins playbook
  hosts: jenkins
  tags:
    - configuration
  gather_facts: yes
  become: yes
  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: jenkins
        group: jenkins
        mode: '0644'
      loop:
      - { src: '/vagrant/jenkins.yml', dest: '/var/lib/jenkins/jenkins.yml' }
    - name: Stop Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: stopped

    - name: Start Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes
    # - name: Create dir
    #   ansible.builtin.file:
    #     path: "{{ item.path }}"
    #     state: "{{ item.state }}"
    #     mode: '0755'
    #   loop:
     
    #  - { path: '/var/lib/jenkins/jobs/build' , state: 'directory'}
    # - name: copy files
    #   copy: src=/vagrant/build/ dest=/var/lib/jenkins/jobs/build/ remote_src=yes directory_mode=yes

    # - name: Copy files
    #   ansible.builtin.copy:
    #     src: "{{ item.src }}"
    #     dest: "{{ item.dest }}"
    #     owner: root
    #     group: root
    #     mode: '0644'
    #   loop:
    #   - { src: '/vagrant/build/*', dest: '/var/lib/jenkins/jobs/' }