---
#Playbook 1
- name: Jenkins playbook
  hosts: jenkins
  gather_facts: yes
  become: yes

  vars:
    jenkins_hostname: localhost
    java_packages: "openjdk-17-jdk" 
    jenkins_http_port: 8989
    jenkins_admin_username: admin
    jenkins_admin_password: admin  

    jenkins_plugins_install_dependencies: true
    jenkins_plugins_state: latest
    jenkins_plugins:              # имена плагинов стоит указывать, как написано в ссылке на плагин, если кликнуть на него из самого jenkins 
      - configuration-as-code     # пример: https://plugins.jenkins.io/golang/ , то есть имя плагина golang
      - nexus-artifact-uploader  
      - git
      - golang
      - ssh
      - ws-cleanup
    jenkins_java_options: "-Dcasc.jenkins.config=${JENKINS_HOME}/casc_configs"

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins 

  post_tasks:
    - name: Create dir
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        group: jenkins
        owner: jenkins
        mode: '0755'
      loop:
      - { path: '/var/lib/jenkins/jobs/build' , state: 'directory'}    
      - { path: '/var/lib/jenkins/casc_configs' , state: 'directory'}   
    
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: jenkins
        group: jenkins
        mode: '0644'
      loop:
      - { src: '/vagrant/jenkins.yml', dest: '/var/lib/jenkins/casc_configs/jenkins.yaml' }
      - { src: '/vagrant/build/config.xml', dest: '/var/lib/jenkins/jobs/build/config.xml' }

    - name: Stop Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: stopped

    - name: Start Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes