---
#Playbook 1
- name: Jenkins playbook
  hosts: jenkins
  tags:
    - configuration
  gather_facts: yes
  become: yes

  vars:
    jenkins_version: "2.442"
    jenkins_hostname: localhost
    jenkins_plugins_install_dependencies: true
    jenkins_plugins_state: present    
    jenkins_plugins:
      - timestamper
      - Workspace Cleanup
      - credentials 
      - credentials-binding
      - locale
      - git
      - timestamper
      - pipeline-groovy-lib
      - workflow-basic-steps
      - workflow-cps
      - workflow-multibranch
      - pipeline-build-step
      - pipeline-input-step
      - pipeline-milestone-step
      - pipeline-stage-step
      - pipeline-model-definition 
      - configuration-as-code 
      - go
    # java_packages:
    #   - openjdk-17-jdk

  pre_tasks:
    - include_tasks: debian-setup.yml
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins

  # tasks:
  #   - name: Create a jenkins job using basic authentication
  #     community.general.jenkins_job:
  #       config: "{{ lookup('file', 'test.xml') }}"
  #       name: test
  #       password: admin
  #       url: http://localhost:8080
  #       user: admin 

  post_tasks:
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8080/"
        status_code:
          - 200
          - 403