---
#Playbook 1
- name: Jenkins playbook
  hosts: jenkins
  tags:
    - configuration
  gather_facts: yes
  become: yes

  vars:
    jenkins_version: "2.443"
    jenkins_hostname: localhost
    jenkins_plugins_install_dependencies: true
    jenkins_plugins_state: present    
    jenkins_plugins:
      - locale
      - git
      - timestamper
      - configuration-as-code 
      - golang
      - prism-api

  pre_tasks:
    - include_tasks: debian-setup.yml
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins 

  post_tasks:
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8080/"
        status_code:
          - 200
          - 403

    - name: Create dir
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        group: jenkins
        owner: jenkins
        mode: '0755'
      loop:
      - { path: '/var/lib/jenkins/jobs/build' , state: 'directory'}    
      - { path: '/var/lib/jenkins/casc_configs' , state: 'directory'} 
      - { path: '/var/lib/jenkins/init.groovy.d' , state: 'directory'}    
    
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: jenkins
        group: jenkins
        mode: '0644'
      loop:
      - { src: '/vagrant/jenkins.yml', dest: '/var/lib/jenkins/casc_jenkins.yaml' }
      - { src: '/vagrant/jenkins.yml', dest: '/var/lib/jenkins/casc_configs/casc_jenkins.yaml' }
      - { src: '/vagrant/jenkins.yml', dest: '/var/lib/jenkins/init.groovy.d/casc_jenkins.yaml' }
      - { src: '/vagrant/build/config.xml', dest: '/var/lib/jenkins/jobs/build/config.xml' }

    - name: Stop Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: stopped

    - name: Start Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes