Vagrant.configure("2") do |config|

    config.vm.synced_folder  ".", "/vagrant", disabled: false   
    config.vm.box = "generic/debian11"
    
    # Jenkins VM config
    config.vm.define "jenkins" do |jenkins|
        jenkins.vm.provider "virtualbox" do |vb|
            vb.memory = 1200
            vb.cpus   = 2
        end
        
        jenkins.vm.network "private_network", ip: "192.168.56.65"
        
        jenkins.vm.provision "shell", inline: <<-SHELL
            apt-get update #--allow-releaseinfo-change
            apt-get install -y build-essential default-jre jq
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            echo "alias ll='ls -l'" >> /root/.bashrc

            # install jenkins
            curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
                /usr/share/keyrings/jenkins-keyring.asc > /dev/null
            echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
                https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
                /etc/apt/sources.list.d/jenkins.list > /dev/null
            apt-get update
            apt-get install jenkins sshpass

            # configure jenkins
            mkdir /var/lib/jenkins/init.groovy.d
            cp /vagrant/scripts/* /var/lib/jenkins/init.groovy.d/
            mkdir /var/lib/jenkins/casc_configs
            cp /vagrant/jenkins.yml /var/lib/jenkins/casc_configs/
            chown -R jenkins:jenkins /var/lib/jenkins/init.groovy.d/
            sed -i 's@^Environment="JAVA_OPTS=-Djava.awt.headless=true"@Environment="JAVA_OPTS=-Djava.awt.headless=true -Dcasc.jenkins.config=${JENKINS_HOME}/casc_configs -Djenkins.install.runSetupWizard=false"@g' /lib/systemd/system/jenkins.service
            # -Dcasc.jenkins.config=${JENKINS_HOME}/casc_configs
            sed -i "s/^#TimeoutStartSec=90/TimeoutStartSec=180/g" /lib/systemd/system/jenkins.service
            
            mkdir /var/lib/jenkins/jobs/action
            cp /vagrant/config.xml /var/lib/jenkins/jobs/action/

            sudo chmod 0755 /var/lib/jenkins/jobs/action
            sudo chown -R jenkins /var/lib/jenkins/jobs/action
            sudo chgrp -R jenkins /var/lib/jenkins/jobs/action
            sudo chmod 0644 /var/lib/jenkins/jobs/action/config.xml 
            sudo chgrp -R jenkins /var/lib/jenkins/jobs/action/config.xml 
            sudo chown -R jenkins /var/lib/jenkins/jobs/action/config.xml 

            cp /vagrant/org.jvnet.hudson.plugins.SSHBuildWrapper.xml /var/lib/jenkins/
            sudo chmod 0644 /var/lib/jenkins/org.jvnet.hudson.plugins.SSHBuildWrapper.xml
            sudo chgrp -R jenkins /var/lib/jenkins/org.jvnet.hudson.plugins.SSHBuildWrapper.xml
            sudo chown -R jenkins /var/lib/jenkins/org.jvnet.hudson.plugins.SSHBuildWrapper.xml
            
            systemctl daemon-reload
            systemctl restart jenkins
        SHELL
    end

    # Nexus VM config
    config.vm.define "nexus" do |nexus|
        nexus.vm.provider("virtualbox"){ |vb| vb.memory = 2048 }
        nexus.vm.network "private_network", ip: "192.168.56.3"
        nexus.vm.network "forwarded_port", guest: 8081, host: 8091
    
        nexus.vm.provision :ansible_local do |ans|
            ans.playbook = "nexus.yaml"
        end
    end

    # Staging VM config
    config.vm.define "staging" do |host|
        host.vm.network "private_network", ip: "192.168.56.61"
        host.vm.provider("virtualbox"){ |vb| vb.memory = 256 }
    end

    # Production VM config
    config.vm.define "production" do |host|
        host.vm.network "private_network", ip: "192.168.56.62"
        host.vm.provider("virtualbox"){ |vb| vb.memory = 256 }
    end

    # Global ssh auth disable
    config.vm.provision "shell", inline: <<-SHELL
        sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
        service sshd restart
        echo -e "vagrant\nvagrant" | passwd vagrant
    SHELL
end