Vagrant.configure("2") do |config|

    config.vm.synced_folder  ".", "/vagrant", disabled: false   
    config.vm.box = "generic/debian12"
    
    config.vm.define "jenkins" do |jenkins|
        jenkins.vm.network "private_network", ip: "192.168.56.2"
        jenkins.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
        jenkins.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get install -y ansible sshpass 
            ansible-galaxy collection install community.general
            export LC_ALL=C.UTF-8
        SHELL
        jenkins.vm.provision :ansible_local do |ansible|
            ansible.playbook       = "playbook.yaml"
            ansible.limit          = "all"
            ansible.inventory_path = "inventory"
        end
    end
end