Vagrant.configure("2") do |config|
    
    config.vm.define "node1" do |node1|
        node1.vm.box = "generic/debian12"
        node1.vm.network "private_network", ip: "192.168.56.31"
        #node1.vm.provision :file, source: '.vagrant/machines/node1/virtualbox/private_key', destination: '/home/vagrant/private_key_node1'
    end

    config.vm.define "node2" do |node2|
        node2.vm.box = "generic/debian12"
        node2.vm.network "private_network", ip: "192.168.56.32"
        #node2.vm.provision :file, source: '.vagrant/machines/node2/virtualbox/private_key', destination: '/home/vagrant/private_key_node2'
    end

    config.vm.define "nginx" do |nginx|
        nginx.vm.box = "generic/debian12"
        nginx.vm.network "private_network", ip: "192.168.56.33"
        #nginx.vm.provision :file, source: '.vagrant/machines/nginx/virtualbox/private_key', destination: '/home/vagrant/private_key_nginx'
        nginx.vm.network "forwarded_port", guest: 80, host: 80, host_ip: "127.0.0.1"
    end
end