Vagrant.configure("2") do |config|

    config.vm.synced_folder  ".", "/vagrant", disabled: false   
    config.vm.box = "generic/debian12"
    
    config.vm.define "node1" do |node1|  
        node1.vm.network "private_network", ip: "192.168.56.31"
    end

    config.vm.define "node2" do |node2|
        node2.vm.network "private_network", ip: "192.168.56.32"
    end

    config.vm.define "nginx" do |nginx|
        nginx.vm.network "private_network", ip: "192.168.56.33"
        nginx.vm.network "forwarded_port", guest: 80, host: 80, host_ip: "127.0.0.1"
        nginx.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get install -y ansible sshpass
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            echo "alias ll='ls -la'" >> /root/.bashrc
        SHELL
        nginx.vm.provision :ansible_local do |ansible|
            ansible.playbook       = "playbook.yaml"
            ansible.limit          = "all"
            ansible.inventory_path = "inventory"
        end
    end
end