- name: My first play
  hosts: myhosts
  tags:
    - configuration
  gather_facts: no
  become: yes
  tasks:
    - name: install packages
      become: yes
      apt:
        pkg:
          - apache2
          - php
          - libapache2-mod-php
        state: present

    - name: Create web page directories and files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        mode: "0755"
      loop:
        - { path: "/var/www/a.example.com", state: "directory" }
        - { path: "/var/www/b.example.com", state: "directory" }

    - name: Copy files with owner and permissions
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - { src: "./index.html", dest: "/var/www/a.example.com/index.html" }
        - { src: "./index.php", dest: "/var/www/b.example.com/index.php" }
        - {
            src: "./a.example.com.conf",
            dest: "/etc/apache2/sites-available/a.example.com.conf",
          }
        - {
            src: "./b.example.com.conf",
            dest: "/etc/apache2/sites-available/b.example.com.conf",
          }

    - name: Add apache listen ports
      ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        line: "{{ item.text }}"
      loop:
        - { path: "/etc/apache2/ports.conf", text: "Listen 8080" }
        - { path: "/etc/apache2/ports.conf", text: "Listen 8081" }

    - name: Create symbolic link
      file:
        src: "{{ item.src}}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - {
            src: "/etc/apache2/sites-available/a.example.com.conf",
            dest: "/etc/apache2/sites-enabled/a.example.com.conf",
          }
        - {
            src: "/etc/apache2/sites-available/b.example.com.conf",
            dest: "/etc/apache2/sites-enabled/b.example.com.conf",
          }

    - name: Reboot apache
      ansible.builtin.reboot:
        msg: "Rebooting apache in 5 seconds"
