Vagrant.configure("2") do |config|

    config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"
    
    config.vm.define "node1" do |node1|
        node1.vm.box = "generic/debian12"
        node1.vm.network "private_network", ip: "192.168.56.21"
        node1.vm.provision :file, source: '.vagrant/machines/node1/virtualbox/private_key', destination: '/home/vagrant/private_key_node1'
    end
end